#!/usr/bin/env python3
from re import search
import sys
import os

t = {}

# curl -LO https://www.unicode.org/Public/UCD/latest/ucd/NamesList.txt
with open('NamesList.txt') as f:
    for s in f:
        if m := search('^([0-9A-F]+)\t.* ([A-Z])( |$)', s):
            codepoint, letter = int(m[1], 16), m[2]

            if 'COMBINING' in s:
                continue
            # ARBIC LETTER WITH ...
            elif 'ARABIC' in s:
                continue
            # SMALL CAPITAL
            elif 'CAPITAL' in s:
                pass
            elif 'SMALL' in s:
                letter = letter.lower()
            else:
                continue

            if codepoint >= 0x1FFFF:
                break

            t[letter] = t.get(letter) or []
            t[letter].append(chr(codepoint))

tab = ' ' * 4

print(f"""\
// This file was generated by {os.path.basename(sys.argv[0])}.
#[rustfmt::skip]
pub const fn get_unicode_variations(c: char) -> &'static [char] {{
{tab}match c {{\
""")
for letter, variations in sorted(t.items()):
    print("{indent}'{left}' => &[{right}],".format(
        indent=tab * 2,
        left=letter,
        right=','.join([f"'{v}'" for v in variations if v != letter]),
    ))
print(f"""\
{tab}{tab}_ => &[],
{tab}}}
}}\
""")
